# Generated by Django 4.1.4 on 2024-05-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermessage",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatbotResponse",
        ),
        migrations.DeleteModel(
            name="UserMessage",
        ),
    ]
